# To auto-connect to Wi-Fi
CIRCUITPY_WIFI_SSID="ANetwork2"
CIRCUITPY_WIFI_PASSWORD="dvhi5728"

# To enable modifying files from the web. Change this too!
# Leave the User field blank in the browser.
CIRCUITPY_WEB_API_PASSWORD="passw0rd"

CIRCUITPY_WEB_API_PORT=80
CIRCUITPY_WEB_INSTANCE_NAME="eCart"